name: Tests
on:
  push:
    branches:
      - main


defaults:
  run:
    shell: 'bash'

jobs:
  e2e:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
        with:
          node-version: 16
      
      - run: npm install

      - run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npm run e2e --if-present
        if: matrix.os == 'ubuntu-latest'

      - run: npm run e2e --if-present
        if: matrix.os != 'ubuntu-latest'
